//ATENCION
export const INSERTAR_ATENCION = "INSERTAR_ATENCION";
export const MOSTRAR_ATENCIONES = "INSERTAR_ATENCIONES";
export const MOSTRAR_ATENCION = "INSERTAR_ATENCION";


//AUTH
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGEDED = "USER_LOGEDED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";


